# 执行周期：cronjob规则
schedule:
  # 每天凌晨运行
  cron: "0 1 * * *"
# 备份配置
configMap:
  env:
    BACKUP_DB_HOST: 127.0.0.1
    BACKUP_DB_PORT: 3306
    BACKUP_USER: root
    BACKUP_PASSWORD: 123456
    # 需要备份的数据库数据库名称，多个使用,分隔
    BACKUP_DB: db_one,db_two_db_three
    # 数据库备份保留个数
    BACKUP_STORAGE_NUMBER: 7
# 存储策略
vc:
  storage:
    size: 50Gi
  nfs:
    host: nfs
    mountPath: /mnt/backup

nodeSelector: {}

tolerations: []

affinity: {}

# 添加image信息
image:
  repository: nekoimi/backup-mysql
  tag: "8.0.33"
